name: clean artifacts
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Required to allow the action to delete artifacts
    steps:
      - name: cleanup
        uses: glassechidna/artifact-cleaner@master
